/**
 * Generates `prisma/bootstrap.sql` — a single self-contained SQL file that
 * creates the schema and the starter data in one paste.
 *
 * It exists for the Neon SQL Editor: it means a first-time deploy needs no
 * local clone, no npm install and no Prisma CLI. Everything the normal
 * `prisma migrate deploy && npm run seed` produces, this file produces too,
 * including the `_prisma_migrations` row so a later `migrate deploy` sees the
 * migration as already applied instead of trying to re-run it.
 *
 * Regenerate with:  npx tsx scripts/make-bootstrap-sql.ts
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import bcrypt from 'bcryptjs';

const MIGRATIONS_DIR = join(process.cwd(), 'prisma', 'migrations');
const OUT = join(process.cwd(), 'prisma', 'bootstrap.sql');

const ADMIN_PASSWORDS = {
  raul: process.env.SEED_RAUL_PASSWORD ?? 'HiOcten#2026raul',
  france: process.env.SEED_FRANCE_PASSWORD ?? 'HiOcten#2026france',
};

/** Single-quote escape for SQL string literals. */
const q = (v: string | null | undefined) =>
  v === null || v === undefined ? 'NULL' : `'${v.replace(/'/g, "''")}'`;

function money(n: number): string {
  return n.toFixed(2);
}

async function main() {
  const dirs = readdirSync(MIGRATIONS_DIR).filter((d) => /^\d{14}_/.test(d)).sort();
  if (dirs.length === 0) throw new Error('no migrations found');

  const parts: string[] = [];

  parts.push(`-- AutoCare bootstrap
--
-- Creates the whole database in one go: schema, migration bookkeeping, and the
-- starter data (admin accounts, service catalog, two sample jobs).
--
-- HOW TO USE
--   1. Open your Neon project -> SQL Editor.
--   2. Paste this entire file and press Run.
--
-- Safe to run once on an empty database. Running it twice will fail on the
-- unique constraints, which is deliberate: it will not silently duplicate data.
--
-- Generated by scripts/make-bootstrap-sql.ts — do not edit by hand.

BEGIN;
`);

  // ---- schema, straight from the Prisma migrations -----------------------
  const migrationRows: { name: string; checksum: string }[] = [];

  for (const dir of dirs) {
    const file = join(MIGRATIONS_DIR, dir, 'migration.sql');
    const sql = readFileSync(file);
    // Prisma's checksum is the SHA-256 of the migration file, hex encoded.
    const checksum = createHash('sha256').update(sql).digest('hex');
    migrationRows.push({ name: dir, checksum });

    parts.push(`-- ============================================================`);
    parts.push(`-- schema from prisma/migrations/${dir}/migration.sql`);
    parts.push(`-- ============================================================\n`);
    parts.push(sql.toString('utf8').trim());
    parts.push('');
  }

  // ---- migration bookkeeping ---------------------------------------------
  parts.push(`
-- ============================================================
-- Prisma migration bookkeeping
-- Records the migration as applied, so a later
--   npx prisma migrate deploy
-- treats the schema as up to date instead of re-running it.
-- ============================================================

CREATE TABLE IF NOT EXISTS "_prisma_migrations" (
    "id"                    VARCHAR(36) PRIMARY KEY NOT NULL,
    "checksum"              VARCHAR(64) NOT NULL,
    "finished_at"           TIMESTAMPTZ,
    "migration_name"        VARCHAR(255) NOT NULL,
    "logs"                  TEXT,
    "rolled_back_at"        TIMESTAMPTZ,
    "started_at"            TIMESTAMPTZ NOT NULL DEFAULT now(),
    "applied_steps_count"   INTEGER NOT NULL DEFAULT 0
);
`);

  for (const row of migrationRows) {
    parts.push(
      `INSERT INTO "_prisma_migrations" ` +
        `("id","checksum","finished_at","migration_name","started_at","applied_steps_count") VALUES ` +
        `(gen_random_uuid()::text, ${q(row.checksum)}, now(), ${q(row.name)}, now(), 1);`,
    );
  }

  // ---- seed data ----------------------------------------------------------
  const raulId = 'seed-user-raul';
  const franceId = 'seed-user-france';

  const raulHash = await bcrypt.hash(ADMIN_PASSWORDS.raul, 12);
  const franceHash = await bcrypt.hash(ADMIN_PASSWORDS.france, 12);

  parts.push(`

-- ============================================================
-- Shop details printed on receipts (editable later in Settings)
-- ============================================================

INSERT INTO "ShopSetting" ("id","name","address","phone","updatedAt") VALUES
  ('shop',
   'HI-OCTEN CAR CARE SERVICES',
   'Blk 4 Lot 3, Villa Acacia St., Bayview Subd., Amaya I, Tanza, Cavite (going Starfish Beach)',
   '09989800388',
   now());

-- ============================================================
-- Owner accounts. Passwords are bcrypt hashes (cost 12) — the plaintext is
-- never stored. Both are flagged mustChangePassword, so the first login goes
-- straight to My Account and asks for a private password before anything
-- else opens. The starting passwords below are public (they are in the
-- README), which is exactly why the flag is set.
-- ============================================================

INSERT INTO "User" ("id","name","username","passwordHash","role","locale","isActive","failedLoginAttempts","tokenVersion","mustChangePassword","createdAt","updatedAt") VALUES
  (${q(raulId)},   'RAUL V. SANTOS',            'raul',   ${q(raulHash)},   'ADMIN', 'fil', true, 0, 0, true, now(), now()),
  (${q(franceId)}, 'Francis Wilfred Antiporda', 'france', ${q(franceHash)}, 'ADMIN', 'fil', true, 0, 0, true, now(), now());
`);

  // Service catalog
  const services = [
    { id: 'seed-svc-carwash', name: 'Carwash', price: 250 },
    { id: 'seed-svc-oilchange', name: 'Oil Change', price: 850 },
    { id: 'seed-svc-tuneup', name: 'Engine Tune-up', price: 1800 },
    { id: 'seed-svc-brake', name: 'Brake Service', price: 1200 },
    { id: 'seed-svc-tire', name: 'Tire Change', price: 400 },
    { id: 'seed-svc-battery', name: 'Battery Replacement', price: 500 },
    { id: 'seed-svc-aircon', name: 'Aircon Cleaning', price: 1500 },
  ];

  parts.push(`
-- ============================================================
-- Starter service catalog
-- ============================================================

INSERT INTO "Service" ("id","name","defaultPrice","isActive","createdAt","updatedAt") VALUES`);
  parts.push(
    services
      .map(
        (s) =>
          `  (${q(s.id)}, ${q(s.name)}, ${money(s.price)}, true, now(), now())`,
      )
      .join(',\n') + ';',
  );

  // Sample customers, vehicles and jobs
  const year = new Date().getFullYear();

  parts.push(`

-- ============================================================
-- Two sample customers, each with a vehicle and one job, so the
-- dashboard and reports are not empty on the first login.
-- Delete them once real jobs start coming in.
-- ============================================================

INSERT INTO "Customer" ("id","fullName","phone","address","createdById","createdAt","updatedAt") VALUES
  ('seed-cust-1', 'Mario Dela Cruz', '09171234567', 'Amaya I, Tanza, Cavite',        ${q(raulId)}, now(), now()),
  ('seed-cust-2', 'Elena Bautista',  '09228887766', 'Bayview Subd., Tanza, Cavite',  ${q(raulId)}, now(), now());

INSERT INTO "Vehicle" ("id","customerId","plateNumber","make","model","year","color","createdAt","updatedAt") VALUES
  ('seed-veh-1', 'seed-cust-1', 'ABC 1234', 'Toyota',     'Vios',   2018, 'Silver', now(), now()),
  ('seed-veh-2', 'seed-cust-2', 'XYZ 5678', 'Mitsubishi', 'Mirage', 2020, 'Red',    now(), now());

-- Job number counter, so the next job recorded in the app is JOB-${year}-0003.
INSERT INTO "JobCounter" ("year","lastNumber") VALUES (${year}, 2);
`);

  // Job 1: unpaid.  200 labour + 320 part + (250 + 850) services = 1620, less 50 discount = 1570
  // Job 2: paid.    350 labour + 80 expenses + 1450 part + (1500 + 1200) services = 4580
  parts.push(`
INSERT INTO "Job" ("id","jobNumber","customerId","vehicleId","mechanicId","date","status",
                   "laborCharge","expenses","discount","subtotal","total","amountPaid","balance",
                   "paymentMethod","notes","createdById","createdAt","updatedAt") VALUES
  ('seed-job-1', 'JOB-${year}-0001', 'seed-cust-1', 'seed-veh-1', ${q(raulId)},
   now() - interval '2 days', 'UNPAID',
   200.00, 0.00, 50.00, 1620.00, 1570.00, 0.00, 1570.00,
   NULL, 'Sample job — delete once you start recording real work.', ${q(franceId)}, now(), now()),

  ('seed-job-2', 'JOB-${year}-0002', 'seed-cust-2', 'seed-veh-2', ${q(raulId)},
   now() - interval '1 day', 'PAID',
   350.00, 80.00, 0.00, 4580.00, 4580.00, 4580.00, 0.00,
   'GCASH', 'Sample job — delete once you start recording real work.', ${q(franceId)}, now(), now());

INSERT INTO "JobService" ("id","jobId","serviceName","price","serviceId") VALUES
  ('seed-js-1', 'seed-job-1', 'Carwash',         250.00,  'seed-svc-carwash'),
  ('seed-js-2', 'seed-job-1', 'Oil Change',      850.00,  'seed-svc-oilchange'),
  ('seed-js-3', 'seed-job-2', 'Aircon Cleaning', 1500.00, 'seed-svc-aircon'),
  ('seed-js-4', 'seed-job-2', 'Brake Service',   1200.00, 'seed-svc-brake');

INSERT INTO "JobPart" ("id","jobId","partName","quantity","unitPrice","lineTotal") VALUES
  ('seed-jp-1', 'seed-job-1', 'Oil Filter',             1, 320.00,  320.00),
  ('seed-jp-2', 'seed-job-2', 'Brake Pad (front set)',  1, 1450.00, 1450.00);

COMMIT;

-- Done. Log in as 'raul' or 'france', accept the Rules of Use, then change
-- both passwords straight away under Users -> Change password.
`);

  writeFileSync(OUT, parts.join('\n'), 'utf8');
  console.log(`wrote ${OUT}`);
  console.log(`migrations embedded: ${migrationRows.map((m) => m.name).join(', ')}`);
}

main();
