// PLACEHOLDER — DO NOT SHIP AS-IS.
//
// This file is normally generated by the FlutterFire CLI:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// The values below are non-functional placeholders so the project compiles in
// mock mode (USE_MOCKS=true, the default), where Firebase is never initialised.
// Before running with `--dart-define=USE_MOCKS=false`, regenerate this file
// against your own Firebase project.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'cyclemind-ai',
    authDomain: 'cyclemind-ai.firebaseapp.com',
    storageBucket: 'cyclemind-ai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'cyclemind-ai',
    storageBucket: 'cyclemind-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'cyclemind-ai',
    storageBucket: 'cyclemind-ai.appspot.com',
    iosBundleId: 'ai.cyclemind.app',
  );
}
