-- AutoCare bootstrap
--
-- Creates the whole database in one go: schema, migration bookkeeping, and the
-- starter data (admin accounts, service catalog, two sample jobs).
--
-- HOW TO USE
--   1. Open your Neon project -> SQL Editor.
--   2. Paste this entire file and press Run.
--
-- Safe to run once on an empty database. Running it twice will fail on the
-- unique constraints, which is deliberate: it will not silently duplicate data.
--
-- Generated by scripts/make-bootstrap-sql.ts — do not edit by hand.

BEGIN;

-- ============================================================
-- schema from prisma/migrations/20260805141346_init/migration.sql
-- ============================================================

-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ADMIN', 'STAFF');

-- CreateEnum
CREATE TYPE "JobStatus" AS ENUM ('PAID', 'UNPAID', 'PARTIAL');

-- CreateEnum
CREATE TYPE "PaymentMethod" AS ENUM ('CASH', 'GCASH', 'OTHER');

-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "role" "Role" NOT NULL DEFAULT 'STAFF',
    "locale" TEXT NOT NULL DEFAULT 'fil',
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "lastLoginAt" TIMESTAMP(3),
    "failedLoginAttempts" INTEGER NOT NULL DEFAULT 0,
    "lockedUntil" TIMESTAMP(3),
    "policyAcceptedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Customer" (
    "id" TEXT NOT NULL,
    "fullName" TEXT NOT NULL,
    "phone" TEXT,
    "address" TEXT,
    "notes" TEXT,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Customer_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Vehicle" (
    "id" TEXT NOT NULL,
    "customerId" TEXT NOT NULL,
    "plateNumber" TEXT NOT NULL,
    "make" TEXT,
    "model" TEXT,
    "year" INTEGER,
    "color" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Vehicle_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Service" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "defaultPrice" DECIMAL(12,2) NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Service_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Job" (
    "id" TEXT NOT NULL,
    "jobNumber" TEXT NOT NULL,
    "customerId" TEXT NOT NULL,
    "vehicleId" TEXT NOT NULL,
    "mechanicId" TEXT,
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" "JobStatus" NOT NULL DEFAULT 'UNPAID',
    "laborCharge" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "expenses" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "discount" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "subtotal" DECIMAL(12,2) NOT NULL,
    "total" DECIMAL(12,2) NOT NULL,
    "amountPaid" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "balance" DECIMAL(12,2) NOT NULL,
    "paymentMethod" "PaymentMethod",
    "notes" TEXT,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Job_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "JobPart" (
    "id" TEXT NOT NULL,
    "jobId" TEXT NOT NULL,
    "partName" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "unitPrice" DECIMAL(12,2) NOT NULL,
    "lineTotal" DECIMAL(12,2) NOT NULL,

    CONSTRAINT "JobPart_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "JobService" (
    "id" TEXT NOT NULL,
    "jobId" TEXT NOT NULL,
    "serviceName" TEXT NOT NULL,
    "price" DECIMAL(12,2) NOT NULL,
    "serviceId" TEXT,

    CONSTRAINT "JobService_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AuditLog" (
    "id" TEXT NOT NULL,
    "userId" TEXT,
    "action" TEXT NOT NULL,
    "entity" TEXT NOT NULL,
    "entityId" TEXT,
    "metadata" JSONB,
    "ipAddress" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ShopSetting" (
    "id" TEXT NOT NULL DEFAULT 'shop',
    "name" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "email" TEXT,
    "footer" TEXT,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ShopSetting_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "JobCounter" (
    "year" INTEGER NOT NULL,
    "lastNumber" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "JobCounter_pkey" PRIMARY KEY ("year")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_username_key" ON "User"("username");

-- CreateIndex
CREATE INDEX "User_role_idx" ON "User"("role");

-- CreateIndex
CREATE INDEX "User_isActive_idx" ON "User"("isActive");

-- CreateIndex
CREATE INDEX "Customer_fullName_idx" ON "Customer"("fullName");

-- CreateIndex
CREATE INDEX "Customer_phone_idx" ON "Customer"("phone");

-- CreateIndex
CREATE INDEX "Customer_createdById_idx" ON "Customer"("createdById");

-- CreateIndex
CREATE INDEX "Vehicle_customerId_idx" ON "Vehicle"("customerId");

-- CreateIndex
CREATE INDEX "Vehicle_plateNumber_idx" ON "Vehicle"("plateNumber");

-- CreateIndex
CREATE UNIQUE INDEX "Service_name_key" ON "Service"("name");

-- CreateIndex
CREATE INDEX "Service_isActive_idx" ON "Service"("isActive");

-- CreateIndex
CREATE UNIQUE INDEX "Job_jobNumber_key" ON "Job"("jobNumber");

-- CreateIndex
CREATE INDEX "Job_customerId_idx" ON "Job"("customerId");

-- CreateIndex
CREATE INDEX "Job_vehicleId_idx" ON "Job"("vehicleId");

-- CreateIndex
CREATE INDEX "Job_date_idx" ON "Job"("date");

-- CreateIndex
CREATE INDEX "Job_status_idx" ON "Job"("status");

-- CreateIndex
CREATE INDEX "Job_createdById_idx" ON "Job"("createdById");

-- CreateIndex
CREATE INDEX "JobPart_jobId_idx" ON "JobPart"("jobId");

-- CreateIndex
CREATE INDEX "JobPart_partName_idx" ON "JobPart"("partName");

-- CreateIndex
CREATE INDEX "JobService_jobId_idx" ON "JobService"("jobId");

-- CreateIndex
CREATE INDEX "JobService_serviceId_idx" ON "JobService"("serviceId");

-- CreateIndex
CREATE INDEX "AuditLog_userId_idx" ON "AuditLog"("userId");

-- CreateIndex
CREATE INDEX "AuditLog_action_idx" ON "AuditLog"("action");

-- CreateIndex
CREATE INDEX "AuditLog_entity_entityId_idx" ON "AuditLog"("entity", "entityId");

-- CreateIndex
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");

-- AddForeignKey
ALTER TABLE "Customer" ADD CONSTRAINT "Customer_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Vehicle" ADD CONSTRAINT "Vehicle_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Job" ADD CONSTRAINT "Job_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Job" ADD CONSTRAINT "Job_vehicleId_fkey" FOREIGN KEY ("vehicleId") REFERENCES "Vehicle"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Job" ADD CONSTRAINT "Job_mechanicId_fkey" FOREIGN KEY ("mechanicId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Job" ADD CONSTRAINT "Job_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "JobPart" ADD CONSTRAINT "JobPart_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "Job"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "JobService" ADD CONSTRAINT "JobService_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "Job"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "JobService" ADD CONSTRAINT "JobService_serviceId_fkey" FOREIGN KEY ("serviceId") REFERENCES "Service"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;


-- ============================================================
-- Prisma migration bookkeeping
-- Records the migration as applied, so a later
--   npx prisma migrate deploy
-- treats the schema as up to date instead of re-running it.
-- ============================================================

CREATE TABLE IF NOT EXISTS "_prisma_migrations" (
    "id"                    VARCHAR(36) PRIMARY KEY NOT NULL,
    "checksum"              VARCHAR(64) NOT NULL,
    "finished_at"           TIMESTAMPTZ,
    "migration_name"        VARCHAR(255) NOT NULL,
    "logs"                  TEXT,
    "rolled_back_at"        TIMESTAMPTZ,
    "started_at"            TIMESTAMPTZ NOT NULL DEFAULT now(),
    "applied_steps_count"   INTEGER NOT NULL DEFAULT 0
);

INSERT INTO "_prisma_migrations" ("id","checksum","finished_at","migration_name","started_at","applied_steps_count") VALUES (gen_random_uuid()::text, '9c1897b7c93fc5ce4fdf68b6eb7f7100d92560dae9038f0e5e70255153252a45', now(), '20260805141346_init', now(), 1);


-- ============================================================
-- Shop details printed on receipts (editable later in Settings)
-- ============================================================

INSERT INTO "ShopSetting" ("id","name","address","phone","updatedAt") VALUES
  ('shop',
   'HI-OCTEN CAR CARE SERVICES',
   'Blk 4 Lot 3, Villa Acacia St., Bayview Subd., Amaya I, Tanza, Cavite (going Starfish Beach)',
   '09989800388',
   now());

-- ============================================================
-- Owner accounts. Passwords are bcrypt hashes (cost 12) — the
-- plaintext is never stored. CHANGE BOTH after the first login:
-- Users -> Change password.
-- ============================================================

INSERT INTO "User" ("id","name","username","passwordHash","role","locale","isActive","failedLoginAttempts","createdAt","updatedAt") VALUES
  ('seed-user-raul',   'RAUL V. SANTOS',            'raul',   '$2a$12$zrP3LUQwkhfp5GnJ.eDaNehcmX8wkrqzXZOAmmiufPHirPomJL.Ti',   'ADMIN', 'fil', true, 0, now(), now()),
  ('seed-user-france', 'Francis Wilfred Antiporda', 'france', '$2a$12$UT1uL4bFkExLcMeMEAPRQeN/kIP1zECioe64ihG8TmtvxFtKxYjGa', 'ADMIN', 'fil', true, 0, now(), now());


-- ============================================================
-- Starter service catalog
-- ============================================================

INSERT INTO "Service" ("id","name","defaultPrice","isActive","createdAt","updatedAt") VALUES
  ('seed-svc-carwash', 'Carwash', 250.00, true, now(), now()),
  ('seed-svc-oilchange', 'Oil Change', 850.00, true, now(), now()),
  ('seed-svc-tuneup', 'Engine Tune-up', 1800.00, true, now(), now()),
  ('seed-svc-brake', 'Brake Service', 1200.00, true, now(), now()),
  ('seed-svc-tire', 'Tire Change', 400.00, true, now(), now()),
  ('seed-svc-battery', 'Battery Replacement', 500.00, true, now(), now()),
  ('seed-svc-aircon', 'Aircon Cleaning', 1500.00, true, now(), now());


-- ============================================================
-- Two sample customers, each with a vehicle and one job, so the
-- dashboard and reports are not empty on the first login.
-- Delete them once real jobs start coming in.
-- ============================================================

INSERT INTO "Customer" ("id","fullName","phone","address","createdById","createdAt","updatedAt") VALUES
  ('seed-cust-1', 'Mario Dela Cruz', '09171234567', 'Amaya I, Tanza, Cavite',        'seed-user-raul', now(), now()),
  ('seed-cust-2', 'Elena Bautista',  '09228887766', 'Bayview Subd., Tanza, Cavite',  'seed-user-raul', now(), now());

INSERT INTO "Vehicle" ("id","customerId","plateNumber","make","model","year","color","createdAt","updatedAt") VALUES
  ('seed-veh-1', 'seed-cust-1', 'ABC 1234', 'Toyota',     'Vios',   2018, 'Silver', now(), now()),
  ('seed-veh-2', 'seed-cust-2', 'XYZ 5678', 'Mitsubishi', 'Mirage', 2020, 'Red',    now(), now());

-- Job number counter, so the next job recorded in the app is JOB-2026-0003.
INSERT INTO "JobCounter" ("year","lastNumber") VALUES (2026, 2);


INSERT INTO "Job" ("id","jobNumber","customerId","vehicleId","mechanicId","date","status",
                   "laborCharge","expenses","discount","subtotal","total","amountPaid","balance",
                   "paymentMethod","notes","createdById","createdAt","updatedAt") VALUES
  ('seed-job-1', 'JOB-2026-0001', 'seed-cust-1', 'seed-veh-1', 'seed-user-raul',
   now() - interval '2 days', 'UNPAID',
   200.00, 0.00, 50.00, 1620.00, 1570.00, 0.00, 1570.00,
   NULL, 'Sample job — delete once you start recording real work.', 'seed-user-france', now(), now()),

  ('seed-job-2', 'JOB-2026-0002', 'seed-cust-2', 'seed-veh-2', 'seed-user-raul',
   now() - interval '1 day', 'PAID',
   350.00, 80.00, 0.00, 4580.00, 4580.00, 4580.00, 0.00,
   'GCASH', 'Sample job — delete once you start recording real work.', 'seed-user-france', now(), now());

INSERT INTO "JobService" ("id","jobId","serviceName","price","serviceId") VALUES
  ('seed-js-1', 'seed-job-1', 'Carwash',         250.00,  'seed-svc-carwash'),
  ('seed-js-2', 'seed-job-1', 'Oil Change',      850.00,  'seed-svc-oilchange'),
  ('seed-js-3', 'seed-job-2', 'Aircon Cleaning', 1500.00, 'seed-svc-aircon'),
  ('seed-js-4', 'seed-job-2', 'Brake Service',   1200.00, 'seed-svc-brake');

INSERT INTO "JobPart" ("id","jobId","partName","quantity","unitPrice","lineTotal") VALUES
  ('seed-jp-1', 'seed-job-1', 'Oil Filter',             1, 320.00,  320.00),
  ('seed-jp-2', 'seed-job-2', 'Brake Pad (front set)',  1, 1450.00, 1450.00);

COMMIT;

-- Done. Log in as 'raul' or 'france', accept the Rules of Use, then change
-- both passwords straight away under Users -> Change password.
